# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'HRZBase' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HRZBase
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'AFNetworking', '~> 3.2.1'
pod 'KafkaRefresh', '~> 1.0.2'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'YYModel', '~> 1.0.4'
pod 'Masonry', '~> 1.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
end
